---
- name: Reload udev
  shell: udevadm control --reload-rules && udevadm trigger

- name: Restart Sunshine  # noqa: command-instead-of-module
  command: systemctl --user restart sunshine
  become: true
  become_user: "{{ sunshine_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ sunshine_uid.stdout }}"

- name: Reload systemd user daemon  # noqa: command-instead-of-module
  command: systemctl --user daemon-reload
  become: true
  become_user: "{{ sunshine_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ sunshine_uid.stdout }}"

- name: Update Grub
  command: update-grub

- name: Restart GDM
  service:
    name: gdm3
    state: restarted
