tailscale_auth_key: ENC[AES256_GCM,data:Rn99EyZYyjIu1p3pNk+USSQEjF+ZjEljbreeSuipKaAOXRNlAARohd/xgVJxITNra4uSOmAP9XA6dJ57hg==,iv:AdowcwKvc1xORCSUxMIYkHW7fTqvQcw6rIhqf4xjN/g=,tag:C2lPJN+0VZ17abYytsFnoA==,type:str]
github_runner_token: ENC[AES256_GCM,data:IYSWVtHTz3dG8KZ7qdfDQmDipxpNXBEg1dYRIDs=,iv:JfmitjzynOwWMKXFV6XjeioRLgBSSxKxiHWS969Kf9s=,tag:Rk469Vir+/o/qzOefl5ojw==,type:str]
desktop_mac_address: ENC[AES256_GCM,data:h3bY870QXq3uO4o58BCBJoU=,iv:awv1NpKVIMFwNQWxzsDSe+cNqjUO+sowEG/oUZGGddg=,tag:jrTPi3q3U+voQ9/A+UDQ0Q==,type:str]
signet_api_token: ENC[AES256_GCM,data:+hrpcD3wSv2tj1sqW4DHDuTcd7N2Dp4hA4EhDDu108E=,iv:Y9fYPBdOhj8ZO7BP0REzV45w5F8dqxyFfqYeFtDzPEY=,tag:U4uazLuaTHWYtV9AFMQ/Dg==,type:str]
sops:
    age:
        - recipient: age1gpgdca2u5x7gtderh9hux5fgkt8nrt7k4u5rumhrjzd8sjt86gss3qcxgn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSVVpL0JldWNZWU13VzB0
            K0FteGdONTRBTG13ditjUm5xSVFqL3dKWkMwClgvSVozd3F6aTNYV1ExN1VkcUp6
            UDR5VEZRek1MVlRGOStJTVlCT3QzQ2cKLS0tIDBGeVlZM3JyR1VQS2hocEgvWHBq
            NVNNWTE3NXE1T3lpRzAwQzQwYUdBbGcKhCZh+bzsmSi7mS0kvnwbxSfSPXLo2/WA
            8GcEE7abZcnyCXjmuHYvHaUaHsy4upSqfEinkQgTRbZDrIlESlADBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T15:33:42Z"
    mac: ENC[AES256_GCM,data:uC8T39cBQ4nDpPBfci1RiKrx0bH7sJRy+LCVayjDM4gIM/vVKnti6q0nrrbnPPXpxJwM5sN9XJdBgXBNNXdcZtEa3ek5qTf1DxfeoCrfPOSYUfng4EJ4DTia48GJqD6Bd/fsYEdu8/Mhj6s/+vFOn8Fp3Lmt5J/Z6gFWka3tlAI=,iv:6HKBdRFNRtFkztKK6dqZlFgG8NVJ9t6bjYMN/bfkRnA=,tag:qRrAJdogoEc3t6oRTmkQvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
